{
 "title": "Oracle ASH Demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ASH Wait Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_ash",
     "select": [
      [
       { "params": [ "event" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "<>", "value": "NONE" },
      { "condition": "AND", "key": "db", "operator": "=", "value": "otsg" }
     ]
    }
   ]
  },
  {
   "title": "ASH Session State",
   "type": "graph",
   "description": "Number of sessions active or waiting",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_session_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "session_state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_ash",
     "select": [
      [
       { "params": [ "session_state" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "otsg" }
     ]
    }
   ]
  },
  {
   "title": "ASH Sessions Blocked",
   "type": "graph",
   "description": "Sessions blocked by other sessions",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_session_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_ash",
     "query": "SELECT count(\"session_id\") as \"sessions blocked\" FROM \"oracle_ash\" WHERE ( \"db\" = 'otsg') AND blocking_session <> 0 AND $timeFilter GROUP BY  session_id,time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "otsg" }
     ]
    }
   ]
  },
  {
   "title": "ASH SQL Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sql_opname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_opname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_ash",
     "select": [
      [
       { "params": [ "sql_opname" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "otsg" }
     ]
    }
   ]
  },
  {
   "title": "ASH Who blocks who",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oracle_ash",
     "query": "SELECT  \"sql_id\",\"blocking_session\", \"session_id\",\"sql_opname\",\"event\",\"program\" FROM \"oracle_ash\" WHERE (\"db\" = 'otsg') AND $timeFilter and blocking_session  <> 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=", "value": "otsg" }
     ]
    }
   ]
  }
 ]
}